//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceLintCLIGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\PLASMA-at-UMass\\ExceLint\\ExceLintRunner.exe")]
        public string excelintrunnerPathDefault {
            get {
                return ((string)(this["excelintrunnerPathDefault"]));
            }
            set {
                this["excelintrunnerPathDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputPathDefault {
            get {
                return ((string)(this["inputPathDefault"]));
            }
            set {
                this["inputPathDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputPathDefault {
            get {
                return ((string)(this["outputPathDefault"]));
            }
            set {
                this["outputPathDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string excelintGTPathDefault {
            get {
                return ((string)(this["excelintGTPathDefault"]));
            }
            set {
                this["excelintGTPathDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string custodesGTPathDefault {
            get {
                return ((string)(this["custodesGTPathDefault"]));
            }
            set {
                this["custodesGTPathDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string javaPathDefault {
            get {
                return ((string)(this["javaPathDefault"]));
            }
            set {
                this["javaPathDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string custodesJARPathDefault {
            get {
                return ((string)(this["custodesJARPathDefault"]));
            }
            set {
                this["custodesJARPathDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool verboseFlagDefault {
            get {
                return ((bool)(this["verboseFlagDefault"]));
            }
            set {
                this["verboseFlagDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool noexitFlagDefault {
            get {
                return ((bool)(this["noexitFlagDefault"]));
            }
            set {
                this["noexitFlagDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool spectralFlagDefault {
            get {
                return ((bool)(this["spectralFlagDefault"]));
            }
            set {
                this["spectralFlagDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool allCellsFlagDefault {
            get {
                return ((bool)(this["allCellsFlagDefault"]));
            }
            set {
                this["allCellsFlagDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columnsFlagDefault {
            get {
                return ((bool)(this["columnsFlagDefault"]));
            }
            set {
                this["columnsFlagDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rowsFlagDefault {
            get {
                return ((bool)(this["rowsFlagDefault"]));
            }
            set {
                this["rowsFlagDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool levelsFlagDefault {
            get {
                return ((bool)(this["levelsFlagDefault"]));
            }
            set {
                this["levelsFlagDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sheetsFlagDefault {
            get {
                return ((bool)(this["sheetsFlagDefault"]));
            }
            set {
                this["sheetsFlagDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool intrinsicFlagDefault {
            get {
                return ((bool)(this["intrinsicFlagDefault"]));
            }
            set {
                this["intrinsicFlagDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cssFlagDefault {
            get {
                return ((bool)(this["cssFlagDefault"]));
            }
            set {
                this["cssFlagDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool inputsTooFlagDefault {
            get {
                return ((bool)(this["inputsTooFlagDefault"]));
            }
            set {
                this["inputsTooFlagDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double thresholdDefault {
            get {
                return ((double)(this["thresholdDefault"]));
            }
            set {
                this["thresholdDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool addrmodeFlagDefalt {
            get {
                return ((bool)(this["addrmodeFlagDefalt"]));
            }
            set {
                this["addrmodeFlagDefalt"] = value;
            }
        }
    }
}
